"""Prompts + chunking for Q2's four sections.

The four instructions are the spec's output contract verbatim: each section has
its own register, and each is generated by its OWN call (see docs/specs/q2-spec.md §2).
"""
from app.shared.llm_client import Message

SYSTEM_PROMPT = (
    "You summarise research papers for a technically literate reader. "
    "Output GitHub-flavoured markdown only — no preamble, no meta-commentary, "
    "no lines like 'Here is the summary'. Use $...$ for inline math and $$...$$ "
    "for display math."
)

_BASE_USER = """Paper title: {title}
Authors: {authors}

--- PAPER TEXT START ---
{context}
--- PAPER TEXT END ---

{instruction}"""

SECTIONS: list[dict] = [
    {
        "key": "technical",
        "label": "Technical summary",
        "instruction": (
            "Write a TECHNICAL SUMMARY (250-400 words) in precise language that assumes "
            "the reader already knows the field. Name the proposed method or architecture, "
            "the components that make it up, the datasets and evaluation metrics, and the "
            "headline results with their numbers where the paper gives them. No analogies, "
            "no hand-holding — an expert should be able to read this and know exactly what "
            "was done and how it performed."
        ),
    },
    {
        "key": "intuition",
        "label": "Intuition",
        "instruction": (
            "Write the INTUITION behind this paper (200-350 words) in plain language for a "
            "smart friend outside the field. No unexplained jargon; if a technical term is "
            "unavoidable, define it in the same sentence. An analogy is welcome if it makes "
            "the central idea clearer. Focus on *why* the approach works and what changed "
            "relative to how things were done before."
        ),
    },
    {
        "key": "prerequisites",
        "label": "Prerequisite learning",
        "instruction": (
            "List 5-10 PREREQUISITE CONCEPTS a reader must already understand to follow this "
            "paper, most important first. Use exactly this markdown format for each:\n"
            "- **Concept name** — one line on why this specific paper needs it.\n"
            "Name concrete things (e.g. 'attention mechanisms', 'contrastive loss', "
            "'the paper this one builds on'), never vague placeholders like 'basic maths' "
            "or 'machine learning knowledge'."
        ),
    },
    {
        "key": "summary",
        "label": "Summary",
        "instruction": (
            "Write a SUMMARY (150-250 words) in the register of a paper abstract: what "
            "problem was addressed, what approach was taken, what the evidence showed, and "
            "what the authors conclude. Ground every claim in the paper text above."
        ),
    },
]

SECTION_KEYS = [s["key"] for s in SECTIONS]
SECTIONS_BY_KEY = {s["key"]: s for s in SECTIONS}

DIGEST_INSTRUCTION = (
    "Extract the factual content of this excerpt as <=250 words of plain prose: the "
    "problem addressed, methods used, datasets, quantitative results, and any limitations. "
    "Convert table and figure content into text where it carries meaning. No opinions, no "
    "evaluation, no preamble."
)


def build_messages(section_key: str, *, title: str, authors: list[str], context: str) -> list[Message]:
    section = SECTIONS_BY_KEY[section_key]
    user = _BASE_USER.format(
        title=title or "(unknown)",
        authors=", ".join(authors) if authors else "(unknown)",
        context=context,
        instruction=section["instruction"],
    )
    return [Message("system", SYSTEM_PROMPT), Message("user", user)]


def build_digest_messages(chunk: str, *, index: int, total: int) -> list[Message]:
    user = (
        f"Excerpt {index + 1} of {total}.\n\n"
        "--- EXCERPT START ---\n"
        f"{chunk}\n"
        "--- EXCERPT END ---\n\n"
        f"{DIGEST_INSTRUCTION}"
    )
    return [Message("system", SYSTEM_PROMPT), Message("user", user)]


def chunk_text(text: str, *, size: int = 8_000, overlap: int = 1_000) -> list[str]:
    """Chunk with `overlap` chars of context carried between consecutive chunks.

    Every chunk except a short final one is exactly `size` chars; each start
    advances by `size - overlap`, so text straddling a boundary appears whole
    in at least one chunk. (A content-based "drop redundant tail" check was
    removed: it misfired on repetitive text, where any shorter final chunk is
    trivially a substring of its predecessor despite containing new content.)
    """
    if len(text) <= size:
        return [text]
    step = max(1, size - overlap)
    return [text[i:i + size] for i in range(0, len(text), step)]